### ISSUE TITLE
How to use it for multiple .png files that are in different folders?

### ISSUE THREAD

**Issue by fireheart2008** [FoxP/PNG-to-ICO#1]
can you adjust the code to make this happen ? or at least adjust the .bat file for drag&drop multiple files from multiple folders?

**Comment by FoxP** [comment]
When you drag&drop files on a .bat script, Windows explorer only passes the first file as argument.

If you want to use it on multiple files or folders, you'll need to use the .exe installer, select multiples files / folder, right clic, and then select "PNG to ICO". I'll work.
